### ISSUE TITLE
PBI 1.4: Frontend Schedule View Design

### ISSUE THREAD

**Issue by casconea** [casconea/Scrumpool-Practice-Project#4]
Description:
To address the student's need for an easier way to access course information, this PBI focuses on designing a schedule view that displays each course’s time and room number in a clear and organized layout. The schedule view will be user-friendly, allowing students to quickly glance at their course details without navigating through multiple pages, helping them avoid being late to class.

Acceptance Criteria:

A wireframe or mockup of the schedule view is created, showing course times and corresponding room numbers.
The design provides a clear and concise overview of the student’s full schedule, with room numbers prominently displayed for easy identification.
The layout is optimized for readability and accessibility, ensuring that students can quickly understand and navigate the information.
Feedback from team members or stakeholders is incorporated into the design before moving to development.

**Comment by Bharathime** [comment]
Frontend Schedule View was designed according to the acceptance criteria, and certain modifications are being worked on.
