### ISSUE TITLE
PBI 1.9: React App Integration

### ISSUE THREAD

**Issue by casconea** [casconea/Scrumpool-Practice-Project#9]
Description:
This PBI focuses on deploying the schedule view feature, which displays room numbers for each registered course, to the production environment. Once live, students will be able to log in and access their personalized schedules with course times and room numbers, meeting their need for quick and easy access to course information as described in User Story 1. This deployment marks the final step in ensuring the feature is fully operational and accessible to all students.

Acceptance Criteria:

The room number schedule view feature is successfully deployed to the production environment.
Students can access the live feature, log in with their V numbers, and view their schedules with accurate room numbers and course times.
The deployment is tested in the production environment to ensure stability, with no critical issues or bugs.
Performance is monitored to ensure the feature functions efficiently and handles student traffic without delays.
Post-deployment support is available to address any issues or feedback from users after the feature goes live.

**Comment by Bharathime** [comment]
<img width="1470" alt="Screenshot 2024-10-23 at 5 38 51 PM" src="https://github.com/user-attachments/assets/7eb24beb-73e6-43f6-ba2c-ee4ab5688cb7">
There is a backend issue with the CSV file upload for the React website.
